apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Adjust based on your available disk space
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  namespace: default
  labels:
    app: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker3
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: local-registry
  ports:
    - protocol: TCP
      port: 5000       # Internal Cluster IP Port
      targetPort: 5000 # Container Port
      nodePort: 30500  # Accessible from any VM IP on your home network