apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edison-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/space0w1/homelab-infrastructure.git' # e.g., https://github.com/username/my-k8s-manifests.git
    targetRevision: HEAD
    path: 'apps'   # e.g., manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true